server:
  port: 8083

spring:
  application:
    name: product-service

  # MongoDB
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/product_db
      auto-index-creation: true

    # Elasticsearch
    elasticsearch:
      uris: http://${ES_HOST:localhost}:9200

    # Redis
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  # Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecom.common.events"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecom.common.events.ProductImportEvent

  cache:
    type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.ecom.product: DEBUG
    org.springframework.data.elasticsearch: INFO
